### ISSUE TITLE
Add additional userscript-specific documentation within readme

### ISSUE THREAD

**Issue by zabe40** [kellnerd/userscript-bundler#3]
For my [youtube link canonicalizer script](https://github.com/zabe40/musicbrainz-userscripts#musicbrainz-youtube-link-canonicalizer) I'd like to have a little explanation for why it's good to use the script and I'd like it to appear under the header for that script rather than all the way at the bottom. I think a good way to achieve this could be to look for `.md` files in the `doc/` folder with the same name as a userscript (or bookmarklet) and include that at the very end of that section of the readme.

**Comment by kellnerd** [comment]
Have you considered using [`EnhancedUserscriptMetadata.features`](https://github.com/kellnerd/userscript-bundler/blob/27f8693668c50122a32bdd342eb420c55aa5b8a2/src/types/UserscriptMetadata.d.ts#L66)? That's the metadata property which I use to include more information than the brief description, see [example](https://github.com/kellnerd/musicbrainz-scripts/blob/45dc2eb3b6bcc753acd59776660b0cfe1c006835/src/userscripts/parseCopyrightNotice.meta.js#L6).

It is only list items with inline markdown though, so please let me know if you still prefer to have a separate markdown file without restrictions instead.
I would probably place it next to the `.user.js` and `.meta.js` files as  `/doc` currently is automatically used for additional README sections after the userscripts and bookmarklets (although I am wondering whether that was just an overly specific idea for my own use case and I could still change that).

**Comment by zabe40** [comment]
I did consider that, but I think what I want would work better as a paragraph than a bulleted list. Additionally, I'm thinking of adding some images to showcase the userscripts, and I'm not sure if those would work in a list.

I could kinda see them in the same folder as `.user.js` and `.meta.js`, but it would definitely make the most sense to me to have all the documentation together under `/doc`. But its your call.

**Comment by kellnerd** [comment]
I have now implemented the automatic detection of Markdown files with the same base name as the userscript inside the documentation folder.
If such files exist, they will be included below the install buttons in the respective userscripts' README sections (instead of being appended to the end of the README).
You have to pin the version to [v0.8.4](https://github.com/kellnerd/userscript-bundler/releases/tag/v0.8.4) in order to test the feature.

**Comment by zabe40** [comment]
This works great, thanks a bunch!
